language: cpp

# blocklist
branches:
  except:
    - circleci

cache:
  bundler: true
  directories:
    - $HOME/source_code

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=serial.MM }

sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran
    - unzip
    - csh
    - flex
    - patch
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
    - xutils-dev
    - clang

install:
    - source devtools/ci/load_functions.sh
    - setup_ambertools # from load_functions

script:
    - echo "skip test for caching first"
      # - run_tests # from load_functions

after_success:
    - echo "Congrats. Happy computing"

notifications:
  email:
    recipients:
      - nhai.qn@gmail.com
    on_success: never # default: change
    on_failure: never # default: always
