language: cpp

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=fast} # AmberTools/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=fast} # AmberTools/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=fast} # AmberTools/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=fast} # AmberTools/test

     - { os: linux, env: PYTHON_VERSION=3.6 CONDA=False TEST_TASK=fast} # Ambertools/test
     - { os: linux, env: PYTHON_VERSION=3.6 CONDA=True TEST_TASK=fast} # AmberTools/test
     - { os: osx,   env: PYTHON_VERSION=3.6 CONDA=False TEST_TASK=fast} # Ambertools/test
     - { os: osx,   env: PYTHON_VERSION=3.6 CONDA=True TEST_TASK=fast} # Ambertools/test

     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=serial.MM} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=serial.QMMM} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=serial.sander.SEBOMD} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=mmpbsa} # Ambertools/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=rism} # Ambertools/test

     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=serial.MM} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=serial.QMMM} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=serial.sander.SEBOMD} # amber17/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=mmpbsa} # Ambertools/test
     - { os: linux, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=rism} # Ambertools/test

     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=serial.MM} # amber17/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=serial.QMMM} # amber17/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=serial.sander.SEBOMD} # amber17/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=mmpbsa} # Ambertools/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=False TEST_TASK=rism} # Ambertools/test    

     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=serial.MM} # amber17/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=serial.QMMM} # amber17/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=serial.sander.SEBOMD} # amber17/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=mmpbsa} # Ambertools/test
     - { os: osx, env: PYTHON_VERSION=2.7 CONDA=True TEST_TASK=rism} # Ambertools/test

sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran
    - unzip
    - csh
    - flex
    - patch
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
    - xutils-dev
    - clang


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew tap homebrew/science;
      brew update;
      brew install netcdf fftw;
      sudo sh devtools/ci/install_gfortran.sh;
    fi

install:
  - source devtools/ci/load_functions.sh
  - setup_ambertools # from load_functions

script:
  - run_tests # from load_functions
  - shell_session_update(){
       echo "dummy";
    };
    
after_success:
    - echo "Congrats. Happy computing"

notifications:
  email:
    recipients:
      - nhai.qn@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
