language: cpp

# blocklist
branches:
  except:
    - circleci

cache:
  bundler: true
  directories:
    - $HOME/source_code

matrix:
  include:
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=fast } # conda=False is tested on circleci?
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=serial.MM.0 }
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=serial.MM.1 }
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=serial.QMMM.0 }
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=serial.QMMM.1 }
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=serial.sander.SEBOMD }
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=mmpbsa }
     - { os: linux, env: PYTHON_VERSION=2.7 conda=False TEST_TASK=rism }

     - { os: linux, env: PYTHON_VERSION=2.7 conda=True TEST_TASK=fast }

sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran
    - unzip
    - csh
    - flex
    - patch
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
    - xutils-dev
    - clang

install:
    - source devtools/ci/load_functions.sh
    - sleep 10 # wait for circleci to download AT
    - setup_ambertools # from load_functions

script:
    - run_tests # from load_functions

after_success:
    - echo "Congrats. Happy computing"

notifications:
  email:
    recipients:
      - amberbot.2017@gmail.com
    on_success: never # default: change
    on_failure: always
